version: "3.8"

services:
  fluentbit:
    image: fluent/fluent-bit:latest
    container_name: fluentbit
    ports:
      - "24224:24224"
    volumes:
      - ./fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - loki
    networks:
      - logging

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 5s
      timeout: 3s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - logging

volumes:
  loki_data:
  grafana_data:

networks:
  logging:
